server:
  port: 8080

spring:
  application:
    name: franchise-management
  r2dbc:
    url: r2dbc:postgresql://switchback.proxy.rlwy.net:41210/railway
    username: postgres
    password: IHPmubXbpogovGBKoCgWgaTaKgJxkZNJ
  datasource:
    driver-class-name: org.postgresql.Driver

adapters:
  r2dbc:
    host: switchback.proxy.rlwy.net
    port: 41210
    database: railway
    schema: public
    username: postgres
    password: IHPmubXbpogovGBKoCgWgaTaKgJxkZNJ

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.data.r2dbc: DEBUG